archzfs_package_group="archzfs-dkms"
zfs_pkgver=${openzfs_version}
zfs_mod_ver="${zfs_pkgver}"
zfs_pkgname="zfs-dkms"
zfs_utils_pkgname="zfs-utils=${zfs_pkgver}"
zfs_dkms_pkgbuild_path="packages/dkms/${zfs_pkgname}"
zfs_src_target="https://github.com/openzfs/zfs/releases/download/zfs-${zfs_pkgver}/zfs-${zfs_pkgver}.tar.gz"
zfs_workdir="\${srcdir}/zfs-${zfs_pkgver}"
zfs_replaces='replaces=("spl-dkms")'
